export const products = [
  {
    id: 1,
    name: 'Surprise',
    price: 110,
    des: 'description',
    image: '/product-box.jpg',
  },
  {
    id: 2,
    name: 'Oneplus',
    price: 35499,
    des: 'description',
    image: '/10pro_S-.jpg',
  },
  {
    id: 3,
    name: 'Window AC',
    price: 33349,
    des: 'description',
    image: '/ac.jpg',
  },
  {
    id: 4,
    name: 'Iphone 13 series',
    price: 49000,
    des: 'description',
    image: '/apple.jpg',
  },
  {
    id: 5,
    name: 'Cannon',
    price: 55699,
    des: 'description',
    image: '/camera.jpg',
  },
  {
    id: 6,
    name: 'Cooler',
    price: 7499,
    des: 'description',
    image: '/coler.jpg',
  },
  {
    id: 7,
    name: 'Ceiling fan',
    price: 2199,
    des: 'description',
    image: '/fan.png',
  },
  {
    id: 8,
    name: 'Juice set',
    price: 749,
    des: 'description',
    image: '/glass.png',
  },
  {
    id: 9,
    name: 'Laptop',
    price: 51299,
    des: 'description',
    image: '/laptop.jpeg',
  },
  {
    id: 10,
    name: 'LED TV',
    price: 41499,
    des: 'description',
    image: '/led_tv.jpg',
  },
  {
    id: 11,
    name: 'OPPO F21 pro',
    price: 24999,
    des: 'description',
    image: '/oppo.jpg',
  },
  {
    id: 12,
    name: 'Shoe',
    price: 1199,
    des: 'description',
    image: '/shoe.png',
  },
  {
    id: 13,
    name: 'Tide',
    price: 149,
    des: 'description',
    image: '/tide.jpeg',
  },
  {
    id: 14,
    name: 'Monitor',
    price: 11999,
    des: 'description',
    image: '/monitor.jpg',
  },
];
